In [6]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/ott_imdb_sql_ready.csv"
)

genre_data = df[
    [
        "title",
        "genres"
    ]
].dropna(
    subset=["genres"]
).copy()

genre_data.head()

,title,genres
0,Dick Johnson Is Dead,Documentaries
1,Ganglands,"Crime TV Shows, International TV Shows, TV Act..."
2,Jailbirds New Orleans,"Docuseries, Reality TV"
3,Midnight Mass,"TV Dramas, TV Horror, TV Mysteries"
4,My Little Pony: A New Generation,Children & Family Movies

In [7]:
# Split the genres into a list of individual genres

genre_data["genres"] = (
    genre_data["genres"]
    .astype(str)
    .str.split(",")
)

In [8]:
# Explode the genres into separate rows

genre_data = genre_data.explode(
    "genres"
)

In [10]:
# Remove leading and trailing whitespace from the genres

genre_data["genres"] = (
    genre_data["genres"]
    .str.strip()
)

genre_data.head(20)

                                 title                    genres
0                 Dick Johnson Is Dead             Documentaries
1                            Ganglands            Crime TV Shows
1                            Ganglands    International TV Shows
1                            Ganglands     TV Action & Adventure
2                Jailbirds New Orleans                Docuseries
2                Jailbirds New Orleans                Reality TV
3                        Midnight Mass                 TV Dramas
3                        Midnight Mass                 TV Horror
3                        Midnight Mass              TV Mysteries
4     My Little Pony: A New Generation  Children & Family Movies
5                              Sankofa                    Dramas
5                              Sankofa        Independent Movies
5                              Sankofa      International Movies
6                         The Starling                  Comedies
6                         The Starling                    Dramas
7  Vendetta: Truth, Lies and The Mafia            Crime TV Shows
7  Vendetta: Truth, Lies and The Mafia                Docuseries
7  Vendetta: Truth, Lies and The Mafia    International TV Shows
8                     Bangkok Breaking            Crime TV Shows
8                     Bangkok Breaking    International TV Shows

In [11]:
print(genre_data.shape)
print(genre_data.head(20))
print(genre_data["genres"].unique()[:20])

(18739, 2)
                                 title                    genres
0                 Dick Johnson Is Dead             Documentaries
1                            Ganglands            Crime TV Shows
1                            Ganglands    International TV Shows
1                            Ganglands     TV Action & Adventure
2                Jailbirds New Orleans                Docuseries
2                Jailbirds New Orleans                Reality TV
3                        Midnight Mass                 TV Dramas
3                        Midnight Mass                 TV Horror
3                        Midnight Mass              TV Mysteries
4     My Little Pony: A New Generation  Children & Family Movies
5                              Sankofa                    Dramas
5                              Sankofa        Independent Movies
5                              Sankofa      International Movies
6                         The Starling                  Comedies
6                         The Starling                    Dramas
7  Vendetta: Truth, Lies and The Mafia            Crime TV Shows
7  Vendetta: Truth, Lies and The Mafia                Docuseries
7  Vendetta: Truth, Lies and The Mafia    International TV Shows
8                     Bangkok Breaking            Crime TV Shows
8                     Bangkok Breaking    International TV Shows
['Documentaries' 'Crime TV Shows' 'International TV Shows'
 'TV Action & Adventure' 'Docuseries' 'Reality TV' 'TV Dramas' 'TV Horror'
 'TV Mysteries' 'Children & Family Movies' 'Dramas' 'Independent Movies'
 'International Movies' 'Comedies' 'British TV Shows' 'Thrillers'
 'Spanish-Language TV Shows' 'Romantic Movies' 'Horror Movies'
 'Sci-Fi & Fantasy']

In [12]:
# Remove Duplicate Relationships

genre_data = genre_data.drop_duplicates()

In [13]:
print(
    "Genre relationships:",
    len(genre_data)
)

Genre relationships: 18418

In [14]:
# Create Unique Genre List

genres = (
    genre_data[
        ["genres"]
    ]
    .drop_duplicates()
    .sort_values("genres")
    .reset_index(drop=True)
)

genres.head(20)

                      genres
0                     Action
1         Action & Adventure
2           Action-Adventure
3                  Adventure
4           Animals & Nature
5                  Animation
6                      Anime
7             Anime Features
8               Anime Series
9                  Anthology
10                  Arthouse
11                      Arts
12              Biographical
13          British TV Shows
14                     Buddy
15  Children & Family Movies
16         Classic & Cult TV
17            Classic Movies
18                  Comedies
19                    Comedy

In [15]:
# Save Genre CSV

genres.to_csv(
    "../data/processed/genres.csv",
    index=False
)

In [16]:
# Save Genre Relationships

genre_data.to_csv(
    "../data/processed/title_genre_relationships.csv",
    index=False
)

In [17]:
import pandas as pd

genres_df = pd.read_csv(
    "../data/processed/genres.csv"
)

print("Shape:", genres_df.shape)
print("Columns:", genres_df.columns.tolist())
print(genres_df.head(20))

Shape: (98, 1)
Columns: ['genres']
                      genres
0                     Action
1         Action & Adventure
2           Action-Adventure
3                  Adventure
4           Animals & Nature
5                  Animation
6                      Anime
7             Anime Features
8               Anime Series
9                  Anthology
10                  Arthouse
11                      Arts
12              Biographical
13          British TV Shows
14                     Buddy
15  Children & Family Movies
16         Classic & Cult TV
17            Classic Movies
18                  Comedies
19                    Comedy

In [19]:
genres_df.rename(
    columns={
        "genres": "genre_name"
    },
    inplace=True
)

genres_df.head(20)

                  genre_name
0                     Action
1         Action & Adventure
2           Action-Adventure
3                  Adventure
4           Animals & Nature
5                  Animation
6                      Anime
7             Anime Features
8               Anime Series
9                  Anthology
10                  Arthouse
11                      Arts
12              Biographical
13          British TV Shows
14                     Buddy
15  Children & Family Movies
16         Classic & Cult TV
17            Classic Movies
18                  Comedies
19                    Comedy

In [20]:
genres_df["genre_name"] = (
    genres_df["genre_name"]
    .astype(str)
    .str.strip()
)

In [21]:
genres_df = genres_df[
    genres_df["genre_name"].notna()
]

genres_df = genres_df[
    genres_df["genre_name"] != ""
]

genres_df = genres_df.drop_duplicates(
    subset=["genre_name"]
).reset_index(drop=True)

In [22]:
print("Total unique genres:", len(genres_df))
print(genres_df.head(30))

Total unique genres: 98
                  genre_name
0                     Action
1         Action & Adventure
2           Action-Adventure
3                  Adventure
4           Animals & Nature
5                  Animation
6                      Anime
7             Anime Features
8               Anime Series
9                  Anthology
10                  Arthouse
11                      Arts
12              Biographical
13          British TV Shows
14                     Buddy
15  Children & Family Movies
16         Classic & Cult TV
17            Classic Movies
18                  Comedies
19                    Comedy
20             Coming of Age
21              Concert Film
22                     Crime
23            Crime TV Shows
24               Cult Movies
25                     Dance
26                  Disaster
27             Documentaries
28               Documentary
29                Docuseries

In [33]:
print(genres_df["genre_name"].tolist())

['Action', 'Action & Adventure', 'Action-Adventure', 'Adventure', 'Animals & Nature', 'Animation', 'Anime', 'Anime Features', 'Anime Series', 'Anthology', 'Arthouse', 'Arts', 'Biographical', 'British TV Shows', 'Buddy', 'Children & Family Movies', 'Classic & Cult TV', 'Classic Movies', 'Comedies', 'Comedy', 'Coming of Age', 'Concert Film', 'Crime', 'Crime TV Shows', 'Cult Movies', 'Dance', 'Disaster', 'Documentaries', 'Documentary', 'Docuseries', 'Drama', 'Dramas', 'Entertainment', 'Faith & Spirituality', 'Faith and Spirituality', 'Family', 'Fantasy', 'Game Show / Competition', 'Historical', 'Horror', 'Horror Movies', 'Independent Movies', 'International', 'International Movies', 'International TV Shows', 'Kids', "Kids' TV", 'Korean TV Shows', 'LGBTQ', 'LGBTQ Movies', 'Lifestyle', 'Medical', 'Military and War', 'Movies', 'Music', 'Music & Musicals', 'Music Videos and Concerts', 'Musical', 'Mystery', 'Parody', 'Reality', 'Reality TV', 'Romance', 'Romantic Comedy', 'Romantic Movies', 'Romantic TV Shows', 'Sci-Fi & Fantasy', 'Science & Nature TV', 'Science Fiction', 'Soap Opera / Melodrama', 'Spanish-Language TV Shows', 'Special Interest', 'Sports', 'Sports Movies', 'Spy/Espionage', 'Stand-Up Comedy', 'Stand-Up Comedy & Talk Shows', 'Superhero', 'Survival', 'Suspense', 'TV Action & Adventure', 'TV Comedies', 'TV Dramas', 'TV Horror', 'TV Mysteries', 'TV Sci-Fi & Fantasy', 'TV Shows', 'TV Thrillers', 'Talk Show', 'Talk Show and Variety', 'Teen TV Shows', 'Thriller', 'Thrillers', 'Travel', 'Unscripted', 'Western', 'Young Adult Audience', 'and Culture']

In [34]:
import pandas as pd

df = pd.read_csv(
    "../data/processed/ott_imdb_sql_ready.csv"
)

staging_df = df[
    [
        "platform",
        "title",
        "genres"
    ]
].dropna(
    subset=["platform", "title", "genres"]
).copy()

In [35]:
staging_df["genres"] = (
    staging_df["genres"]
    .astype(str)
    .str.split(",")
)

In [36]:
staging_df = staging_df.explode(
    "genres"
)

In [37]:
staging_df["genres"] = (
    staging_df["genres"]
    .str.strip()
)

In [38]:
staging_df.rename(
    columns={
        "genres": "genre_name"
    },
    inplace=True
)

In [39]:
staging_df = staging_df.drop_duplicates(
    subset=[
        "platform",
        "title",
        "genre_name"
    ]
).reset_index(drop=True)

In [40]:
print("Genre relationships:", len(staging_df))
print(staging_df.head(20))

Genre relationships: 18422
   platform                                title                genre_name
0   Netflix                 Dick Johnson Is Dead             Documentaries
1   Netflix                            Ganglands            Crime TV Shows
2   Netflix                            Ganglands    International TV Shows
3   Netflix                            Ganglands     TV Action & Adventure
4   Netflix                Jailbirds New Orleans                Docuseries
5   Netflix                Jailbirds New Orleans                Reality TV
6   Netflix                        Midnight Mass                 TV Dramas
7   Netflix                        Midnight Mass                 TV Horror
8   Netflix                        Midnight Mass              TV Mysteries
9   Netflix     My Little Pony: A New Generation  Children & Family Movies
10  Netflix                              Sankofa                    Dramas
11  Netflix                              Sankofa        Independent Movies
12  Netflix                              Sankofa      International Movies
13  Netflix                         The Starling                  Comedies
14  Netflix                         The Starling                    Dramas
15  Netflix  Vendetta: Truth, Lies and The Mafia            Crime TV Shows
16  Netflix  Vendetta: Truth, Lies and The Mafia                Docuseries
17  Netflix  Vendetta: Truth, Lies and The Mafia    International TV Shows
18  Netflix                     Bangkok Breaking            Crime TV Shows
19  Netflix                     Bangkok Breaking    International TV Shows

In [41]:
staging_df.to_csv(
    "../data/processed/genre_staging.csv",
    index=False
)

print("genre_staging.csv created successfully!")

genre_staging.csv created successfully!

In [42]:
sql_values = ",\n".join(
    "("
    f"'{str(row.platform).replace(chr(39), chr(39)+chr(39))}', "
    f"'{str(row.title).replace(chr(39), chr(39)+chr(39))}', "
    f"'{str(row.genre_name).replace(chr(39), chr(39)+chr(39))}'"
    ")"
    for row in staging_df.itertuples(index=False)
)

sql_script = (
    "INSERT INTO genre_staging "
    "(platform, title, genre_name)\nVALUES\n"
    + sql_values
    + ";"
)

print(sql_script[:5000])

INSERT INTO genre_staging (platform, title, genre_name)
VALUES
('Netflix', 'Dick Johnson Is Dead', 'Documentaries'),
('Netflix', 'Ganglands', 'Crime TV Shows'),
('Netflix', 'Ganglands', 'International TV Shows'),
('Netflix', 'Ganglands', 'TV Action & Adventure'),
('Netflix', 'Jailbirds New Orleans', 'Docuseries'),
('Netflix', 'Jailbirds New Orleans', 'Reality TV'),
('Netflix', 'Midnight Mass', 'TV Dramas'),
('Netflix', 'Midnight Mass', 'TV Horror'),
('Netflix', 'Midnight Mass', 'TV Mysteries'),
('Netflix', 'My Little Pony: A New Generation', 'Children & Family Movies'),
('Netflix', 'Sankofa', 'Dramas'),
('Netflix', 'Sankofa', 'Independent Movies'),
('Netflix', 'Sankofa', 'International Movies'),
('Netflix', 'The Starling', 'Comedies'),
('Netflix', 'The Starling', 'Dramas'),
('Netflix', 'Vendetta: Truth, Lies and The Mafia', 'Crime TV Shows'),
('Netflix', 'Vendetta: Truth, Lies and The Mafia', 'Docuseries'),
('Netflix', 'Vendetta: Truth, Lies and The Mafia', 'International TV Shows'),
('Netflix', 'Bangkok Breaking', 'Crime TV Shows'),
('Netflix', 'Bangkok Breaking', 'International TV Shows'),
('Netflix', 'Bangkok Breaking', 'TV Action & Adventure'),
('Netflix', 'Je Suis Karl', 'Dramas'),
('Netflix', 'Je Suis Karl', 'International Movies'),
('Netflix', 'Confessions of an Invisible Girl', 'Children & Family Movies'),
('Netflix', 'Confessions of an Invisible Girl', 'Comedies'),
('Netflix', 'Crime Stories: India Detectives', 'British TV Shows'),
('Netflix', 'Crime Stories: India Detectives', 'Crime TV Shows'),
('Netflix', 'Crime Stories: India Detectives', 'Docuseries'),
('Netflix', 'Intrusion', 'Thrillers'),
('Netflix', 'Jaguar', 'International TV Shows'),
('Netflix', 'Jaguar', 'Spanish-Language TV Shows'),
('Netflix', 'Jaguar', 'TV Action & Adventure'),
('Netflix', 'Monsters Inside: The 24 Faces of Billy Milligan', 'Crime TV Shows'),
('Netflix', 'Monsters Inside: The 24 Faces of Billy Milligan', 'Docuseries'),
('Netflix', 'Monsters Inside: The 24 Faces of Billy Milligan', 'International TV Shows'),
('Netflix', 'Jeans', 'Comedies'),
('Netflix', 'Jeans', 'International Movies'),
('Netflix', 'Jeans', 'Romantic Movies'),
('Netflix', 'Grown Ups', 'Comedies'),
('Netflix', 'Dark Skies', 'Horror Movies'),
('Netflix', 'Dark Skies', 'Sci-Fi & Fantasy'),
('Netflix', 'Paranoia', 'Thrillers'),
('Netflix', 'Ankahi Kahaniya', 'Dramas'),
('Netflix', 'Ankahi Kahaniya', 'Independent Movies'),
('Netflix', 'Ankahi Kahaniya', 'International Movies'),
('Netflix', 'Chicago Party Aunt', 'TV Comedies'),
('Netflix', 'Squid Game', 'International TV Shows'),
('Netflix', 'Squid Game', 'TV Dramas'),
('Netflix', 'Squid Game', 'TV Thrillers'),
('Netflix', 'The Father Who Moves Mountains', 'Dramas'),
('Netflix', 'The Father Who Moves Mountains', 'International Movies'),
('Netflix', 'The Father Who Moves Mountains', 'Thrillers'),
('Netflix', 'He-Man and the Masters of the Universe', 'Kids'' TV'),
('Netflix', 'He-Man and the Masters of the Universe', 'TV Sci-Fi & Fantasy'),
('Netflix', 'Jaws: The Revenge', 'Action & Adventure'),
('Netflix', 'Jaws: The Revenge', 'Horror Movies'),
('Netflix', 'Jaws: The Revenge', 'Thrillers'),
('Netflix', 'Safe House', 'Action & Adventure'),
('Netflix', 'The Smart Money Woman', 'International TV Shows'),
('Netflix', 'The Smart Money Woman', 'Romantic TV Shows'),
('Netflix', 'The Smart Money Woman', 'TV Comedies'),
('Netflix', 'Training Day', 'Dramas'),
('Netflix', 'Training Day', 'Thrillers'),
('Netflix', 'Dharmakshetra', 'International TV Shows'),
('Netflix', 'Dharmakshetra', 'TV Dramas'),
('Netflix', 'Dharmakshetra', 'TV Sci-Fi & Fantasy'),
('Netflix', 'InuYasha the Movie 2: The Castle Beyond the Looking Glass', 'Action & Adventure'),
('Netflix', 'InuYasha the Movie 2: The Castle Beyond the Looking Glass', 'Anime Features'),
('Netflix', 'InuYasha the Movie 2: The Castle Beyond the Looking Glass', 'International Movies'),
('Netflix', 'InuYasha the Movie 3: Swords of an Honorable Ruler', 'Action & Adventure'),
('Netflix', 'InuYasha the Movie 3: Swords of an Honorable Ruler', 'Anime Features'),
('Netflix', 'InuYasha the Movie 3: Swords of an Honorable Ruler', 'International Movies'),
('Netflix', 'InuYasha the Movie 4: Fire on the Mystic Island', 'Action & Adventure'),
('Netflix', 'InuYasha the Movie 4: Fire on the Mystic Island', 'Anime Features'),
('Netflix', 'InuYasha the Movie 4: Fire on the Mystic Island', 'International Movies'),
('Netflix', 'InuYasha the Movie: Affections Touching Across Time', 'Action & Adventure'),
('Netflix', 'InuYasha the Movie: Affections Touching Across Time', 'Anime Features'),
('Netflix', 'InuYasha the Movie: Affections Touching Across Time', 'International Movies'),
('Netflix', 'Naruto Shippuden the Movie: Blood Prison', 'Action & Adventure'),
('Netflix', 'Naruto Shippuden the Movie: Blood Prison', 'Anime Features'),
('Netflix', 'Naruto Shippuden the Movie: Blood Prison', 'International Movies'),
('Netflix', 'Naruto the Movie 2: Legend of the Stone of Gelel', 'Action & Adventure'),

In [43]:
with open(
    "../data/processed/genre_staging_insert.sql",
    "w",
    encoding="utf-8"
) as f:
    f.write(sql_script)

print("SQL file created!")

SQL file created!